/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import archivoscsv.ArchivoCSV;
import archivoscsv.Controlador;
import archivoscsv.Usuario;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author RafaelPerea
 */
public class InicioSesion extends javax.swing.JFrame {
    ArrayList <Usuario> usuarios = new ArrayList();
    ArchivoCSV csv = new ArchivoCSV();

    /**
     * Creates new form InicioSesion
     */
    public InicioSesion() {
        initComponents();
        csv.leerArchivoUsuario("C:\\Users\\betoh\\OneDrive\\Documentos\\4th semester\\Software design\\Usuarios.csv");
        csv.getUsuarios(usuarios);
        
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JlabelTituloInicioSesion = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        Usuario = new javax.swing.JTextField();
        jSeparatorUsuario = new javax.swing.JSeparator();
        jLabelContraseña = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        jSeparatorPassword = new javax.swing.JSeparator();
        ButtonIngresar = new javax.swing.JButton();
        ButtonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JlabelTituloInicioSesion.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        JlabelTituloInicioSesion.setText("INICIAR SESIÓN");
        jPanel1.add(JlabelTituloInicioSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabelUsuario.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelUsuario.setText("Usuario");
        jPanel1.add(jLabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        Usuario.setForeground(new java.awt.Color(204, 204, 204));
        Usuario.setText("Ingrese su nombre de usuario");
        Usuario.setBorder(null);
        Usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UsuarioMouseClicked(evt);
            }
        });
        Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 341, 30));
        jPanel1.add(jSeparatorUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 341, 10));

        jLabelContraseña.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelContraseña.setText("Contraseña");
        jPanel1.add(jLabelContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        Password.setForeground(new java.awt.Color(204, 204, 204));
        Password.setText("************");
        Password.setBorder(null);
        Password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PasswordMouseClicked(evt);
            }
        });
        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });
        jPanel1.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 341, 30));
        jPanel1.add(jSeparatorPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 341, 10));

        ButtonIngresar.setBackground(new java.awt.Color(204, 204, 204));
        ButtonIngresar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ButtonIngresar.setText("Ingresar");
        ButtonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonIngresarActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 90, 30));

        ButtonSalir.setBackground(new java.awt.Color(204, 204, 204));
        ButtonSalir.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ButtonSalir.setText("Salir");
        ButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSalirActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 90, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonIngresarActionPerformed
        // TODO add your handling code here:
        Controlador controlador=new Controlador();
        JFrame jFrame = new JFrame();
        Interfaz interfaz=new Interfaz();
        boolean verdadero=false;
        
        String nombreUsuario=Usuario.getText();
        
        String pass ="";
        char[] password=Password.getPassword();
        for(int i=0;i<password.length;i++){
            pass+=password[i];
        }
        Usuario usuario= new Usuario(nombreUsuario,pass);
      
        //controlador.validarOpcion(usuario);    
        if(nombreUsuario.isEmpty()||pass.isEmpty()){
            JOptionPane.showMessageDialog(jFrame, "Campos vacíos, por favor ingrese los datos");
        }
        else{
             for(Usuario a: usuarios){
                boolean comparacionUsuarios = a.compararUsuarios(usuario);
        
             if(comparacionUsuarios){
                System.out.println("verdadero");
                interfaz.setVisible(true);
                 verdadero=true;
             }  
             } 
             if(!verdadero){
                JOptionPane.showMessageDialog(jFrame, "Usuario o contraseña incorrecta");
                System.out.println("falso");
             }
            
        }
    }//GEN-LAST:event_ButtonIngresarActionPerformed

    private void ButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ButtonSalirActionPerformed

    private void UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_UsuarioActionPerformed

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_PasswordActionPerformed

    private void UsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsuarioMouseClicked
        // TODO add your handling code here:
       Usuario.setText("");
       Usuario.setForeground(Color.BLACK);
    }//GEN-LAST:event_UsuarioMouseClicked

    private void PasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordMouseClicked
        // TODO add your handling code here:
        Password.setText("");
        Password.setForeground(Color.black);
    }//GEN-LAST:event_PasswordMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonIngresar;
    private javax.swing.JButton ButtonSalir;
    private javax.swing.JLabel JlabelTituloInicioSesion;
    private javax.swing.JPasswordField Password;
    private javax.swing.JTextField Usuario;
    private javax.swing.JLabel jLabelContraseña;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparatorPassword;
    private javax.swing.JSeparator jSeparatorUsuario;
    // End of variables declaration//GEN-END:variables
}
