/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import org.xml.sax.Attributes;
import archivoscsv.Alumno;
import archivoscsv.ArchivoCSV;
import archivoscsv.ArchivoPDF;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rafaelPerea
 */
public class Interfaz extends javax.swing.JFrame {
    private static int indice=0;
    ArchivoCSV csv = new ArchivoCSV();
    ArchivoPDF pdf= new ArchivoPDF();
    JFrame jFrame = new JFrame();

    ArrayList<Alumno> alumno= new ArrayList();
    DefaultTableModel table;
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        
        initComponents(); 
        csv.leerArchivoAlumno("C:\\Users\\betoh\\Downloads\\Others\\ListaAlumnos.csv");
        csv.getAlumnos(alumno);
        Object fila[]=new Object[4];
        this.table = (DefaultTableModel)jTableAlumnos.getModel();
        for(Alumno a: alumno){
            a.setCalificacion("S/C");
            /*System.out.println(a.getMatricula());
            fila[0]=a.getMatricula();
            fila[1]=a.getNombres();
            fila[2]=a.getPrimerApellido();
            fila[3]=a.getSegundoApellido();*/
            table.addRow(new Object[]{a.getMatricula(),a.getNombres(),a.getPrimerApellido(),a.getSegundoApellido(),a.getCalificacion()});
        }
        setTexts(indice); 
        
    }
    
    
    public void setTexts(int indice){
       Matricula.setText(String.valueOf(this.alumno.get(indice).getMatricula()));
       Nombres.setText(this.alumno.get(indice).getNombres());
       ApellidoP.setText(this.alumno.get(indice).getPrimerApellido());
       ApellidoM.setText(this.alumno.get(indice).getSegundoApellido());
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelRegistroCalificacionesTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAlumnos = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelAlumnos = new javax.swing.JLabel();
        jPanelAlumnos = new javax.swing.JPanel();
        jLabelMatricula = new javax.swing.JLabel();
        jLabelNombres = new javax.swing.JLabel();
        jLabelApellidoP = new javax.swing.JLabel();
        jLabelApellidoM = new javax.swing.JLabel();
        jLabelMateria = new javax.swing.JLabel();
        jLabelCalificacion = new javax.swing.JLabel();
        Matricula = new javax.swing.JTextField();
        Nombres = new javax.swing.JTextField();
        ApellidoP = new javax.swing.JTextField();
        ApellidoM = new javax.swing.JTextField();
        Calificacion = new javax.swing.JTextField();
        Materia = new javax.swing.JComboBox<>();
        Guardar = new javax.swing.JButton();
        BotonAnterior = new javax.swing.JButton();
        BotonActualizar = new javax.swing.JButton();
        BotonSiguiente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelRegistroCalificacionesTitulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabelRegistroCalificacionesTitulo.setText("Registro de calificaciones");
        jPanel1.add(jLabelRegistroCalificacionesTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jTableAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Matricula", "Nombres", "Apellido Paterno", "Apellido Materno", "Calificaciones"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableAlumnos);
        if (jTableAlumnos.getColumnModel().getColumnCount() > 0) {
            jTableAlumnos.getColumnModel().getColumn(0).setResizable(false);
            jTableAlumnos.getColumnModel().getColumn(1).setResizable(false);
            jTableAlumnos.getColumnModel().getColumn(2).setResizable(false);
            jTableAlumnos.getColumnModel().getColumn(3).setResizable(false);
            jTableAlumnos.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 540, 290));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));

        jLabelAlumnos.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelAlumnos.setText("Alumnos");
        jPanel1.add(jLabelAlumnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jPanelAlumnos.setBackground(new java.awt.Color(255, 255, 255));
        jPanelAlumnos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelMatricula.setText("Matrícula");

        jLabelNombres.setText("Nombres");

        jLabelApellidoP.setText("Apellido P.");

        jLabelApellidoM.setText("Apellido M.");

        jLabelMateria.setText("Materia");

        jLabelCalificacion.setText("Calificación");

        Matricula.setEditable(false);
        Matricula.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Matricula.setForeground(new java.awt.Color(204, 204, 204));
        Matricula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MatriculaMouseClicked(evt);
            }
        });
        Matricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MatriculaActionPerformed(evt);
            }
        });

        Nombres.setEditable(false);
        Nombres.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Nombres.setForeground(new java.awt.Color(204, 204, 204));
        Nombres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NombresMouseClicked(evt);
            }
        });
        Nombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombresActionPerformed(evt);
            }
        });

        ApellidoP.setEditable(false);
        ApellidoP.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ApellidoP.setForeground(new java.awt.Color(204, 204, 204));
        ApellidoP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ApellidoPMouseClicked(evt);
            }
        });

        ApellidoM.setEditable(false);
        ApellidoM.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ApellidoM.setForeground(new java.awt.Color(204, 204, 204));
        ApellidoM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ApellidoMMouseClicked(evt);
            }
        });

        Calificacion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Calificacion.setForeground(new java.awt.Color(204, 204, 204));
        Calificacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CalificacionMouseClicked(evt);
            }
        });
        Calificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CalificacionKeyTyped(evt);
            }
        });

        Materia.setForeground(new java.awt.Color(204, 204, 204));
        Materia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Diseño de software" }));
        Materia.setBorder(null);

        Guardar.setText("Guardar");
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAlumnosLayout = new javax.swing.GroupLayout(jPanelAlumnos);
        jPanelAlumnos.setLayout(jPanelAlumnosLayout);
        jPanelAlumnosLayout.setHorizontalGroup(
            jPanelAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlumnosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelAlumnosLayout.createSequentialGroup()
                        .addGroup(jPanelAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelMatricula)
                            .addComponent(jLabelNombres)
                            .addComponent(jLabelMateria)
                            .addComponent(jLabelCalificacion)
                            .addComponent(jLabelApellidoP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(2, 2, 2))
                    .addComponent(jLabelApellidoM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Nombres, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ApellidoP, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ApellidoM, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Calificacion)
                    .addComponent(Matricula)
                    .addComponent(Materia, 0, 159, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAlumnosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Guardar)
                .addGap(25, 25, 25))
        );
        jPanelAlumnosLayout.setVerticalGroup(
            jPanelAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlumnosLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanelAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMatricula)
                    .addComponent(Matricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanelAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombres)
                    .addComponent(Nombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanelAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelApellidoP)
                    .addComponent(ApellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanelAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelApellidoM)
                    .addComponent(ApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanelAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMateria)
                    .addComponent(Materia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanelAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCalificacion)
                    .addComponent(Calificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(Guardar)
                .addGap(21, 21, 21))
        );

        jPanel1.add(jPanelAlumnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 260, 350));

        BotonAnterior.setText("Anterior");
        BotonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAnteriorActionPerformed(evt);
            }
        });
        jPanel1.add(BotonAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, -1));

        BotonActualizar.setText("Actualizar");
        BotonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(BotonActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 430, -1, -1));

        BotonSiguiente.setText("Siguiente");
        BotonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSiguienteActionPerformed(evt);
            }
        });
        jPanel1.add(BotonSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 842, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAnteriorActionPerformed
        // TODO add your handling code here:

       if(indice<=0){
           JOptionPane.showMessageDialog(jFrame, "NO SE ENCUENTRAN MÁS ALUMNOS");
       }else{
           indice--;
           setTexts(indice);
       }
       Calificacion.setText("");
       
    }//GEN-LAST:event_BotonAnteriorActionPerformed

    private void MatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MatriculaActionPerformed
        // TODO add your handling code here:
      // Matricula.setText(String.valueOf(this.alumno.get(indice).getMatricula()));
    }//GEN-LAST:event_MatriculaActionPerformed

    private void NombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombresActionPerformed

    private void MatriculaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MatriculaMouseClicked
        // TODO add your handling code here
    }//GEN-LAST:event_MatriculaMouseClicked

    private void NombresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NombresMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_NombresMouseClicked

    private void ApellidoPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ApellidoPMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ApellidoPMouseClicked

    private void ApellidoMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ApellidoMMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ApellidoMMouseClicked

    private void CalificacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CalificacionMouseClicked
        // TODO add your handling code here:
        Calificacion.setText("");
        Calificacion.setForeground(Color.black);
    }//GEN-LAST:event_CalificacionMouseClicked

    private void BotonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSiguienteActionPerformed
        // TODO add your handling code here:        
        if(indice>=alumno.size()-1){
           JOptionPane.showMessageDialog(jFrame, "NO SE ENCUENTRAN MÁS ALUMNOS");
        }else{
           indice++;
           setTexts(indice);
        }
        Calificacion.setText("");
        
    }//GEN-LAST:event_BotonSiguienteActionPerformed

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        // TODO add your handling code here:
        int calif=0;
        String calificacion="";
        Alumno alumnado=alumno.get(indice);
            if(Calificacion.getText().isEmpty()){
                alumnado.setCalificacion("S/C");
                table.setValueAt("S/C", indice, 4);
            }else{
                calif= Integer.parseInt(Calificacion.getText());
                if(calif>=0&&calif<=100){
                  //  table.addRow(new Object[]{alumnado.getMatricula(),alumnado.getNombres(),alumnado.getPrimerApellido(),alumnado.getSegundoApellido(),calificacion});
                  calificacion=String.valueOf(calif);
                  alumnado.setCalificacion(calificacion);
                  table.setValueAt(calificacion, indice, 4);
                }else{
                    JOptionPane.showMessageDialog(jFrame, "INGRESO NO VÁLIDO");
                }  
            }
        
            
            //this.table = (DefaultTableModel)jTableAlumnos.getModel();
            
            
    }//GEN-LAST:event_GuardarActionPerformed

    private void CalificacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CalificacionKeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();
        boolean numeros = key >= 48 && key <= 57;
        if (!numeros)
        {
            evt.consume();
        }
    }//GEN-LAST:event_CalificacionKeyTyped

    private void BotonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonActualizarActionPerformed
        // TODO add your handling code here:
        csv.exportarArchivoCSVAlumno(alumno);
        pdf.crearArchivo(alumno);
        JOptionPane.showMessageDialog(jFrame, "ARCHIVOS CREADOS EXITOSAMENTE");
    }//GEN-LAST:event_BotonActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ApellidoM;
    private javax.swing.JTextField ApellidoP;
    private javax.swing.JButton BotonActualizar;
    private javax.swing.JButton BotonAnterior;
    private javax.swing.JButton BotonSiguiente;
    private javax.swing.JTextField Calificacion;
    private javax.swing.JButton Guardar;
    private javax.swing.JComboBox<String> Materia;
    private javax.swing.JTextField Matricula;
    private javax.swing.JTextField Nombres;
    private javax.swing.JLabel jLabelAlumnos;
    private javax.swing.JLabel jLabelApellidoM;
    private javax.swing.JLabel jLabelApellidoP;
    private javax.swing.JLabel jLabelCalificacion;
    private javax.swing.JLabel jLabelMateria;
    private javax.swing.JLabel jLabelMatricula;
    private javax.swing.JLabel jLabelNombres;
    private javax.swing.JLabel jLabelRegistroCalificacionesTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelAlumnos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableAlumnos;
    // End of variables declaration//GEN-END:variables
}
